### ISSUE TITLE
Fails when multiple measurements included

### ISSUE THREAD

**Issue by saty9** [plate0/ingredient-parser#4]
https://www.bbc.co.uk/food/recipes/chinese_chicken_curry_90700

BBC food website and others list metric and then imperial units with a / in between them which parseIngredients gets stuck with and only takes the amount and misses the unit.

**Comment by ethanmick** [comment]
Hello! It seems the reasonable thing to do will be to parse the fist amount and unit and ignore everything after the `/` for the second pair.

It does bring up an interesting question of how to handle multiple amounts and units, but I think it's fine to consider the first canonical and the second a "rough translation" of the first. If you want to know the amounts in a different unit you can convert it.

We'll add this use case shortly. And _thank you so much_ for giving us a test recipe!

**Comment by saty9** [comment]
Not sure from your comment if this would remove the "rough translation" this would be my preference but maybe add a list of alternative units for people who want that information?

**Comment by ethanmick** [comment]
@saty9 Yes, this fix will do it's best to parse the amount and unit before the `/` and remove any other unit/amount pair. This did surface another issue with our parser not doing a great job handling units with spaces, but I'm now tracking that as #6.
